In [1]:
import numpy as np
import plotly.express as px

In [2]:
mat = np.array([[2,1],[0,1]])
I =  np.array([[1,0],[0,1]])

In [3]:
mat

array([[2, 1],
       [0, 1]])

In [4]:
eigenvalues = np.linalg.eigvals(mat)
eigenvectors = np.linalg.eig(mat).eigenvectors

In [5]:
eigenvalues, eigenvectors

(array([2., 1.]),
 array([[ 1.        , -0.70710678],
        [ 0.        ,  0.70710678]]))

In [46]:
eigenvector_1_antes = eigenvectors[:,0].reshape(2,1)
eigenvector_1_despues = np.matmul(mat,eigenvector_1_antes)
eigenvector_1_despues

array([[2.],
       [0.]])

In [47]:
eigenvector_1_antes

array([[1.],
       [0.]])

In [38]:
np.linalg.norm(eigenvector_1_despues)

np.float64(3.4494897427831788)

In [5]:
grid_size = 1
step = 0.2
xs = np.arange(-grid_size,grid_size+1, step)
ys = np.arange(-grid_size,grid_size+1, step)
xs, ys = np.meshgrid(xs, ys)
points = np.vstack([xs.ravel(), ys.ravel()])

In [13]:
points2 = np.zeros_like(points)
var = 0
eigenvals = I * var

for i in range(points.shape[1]):
    mult = np.matmul(mat - eigenvals, points[:,i].reshape([2,1]))
    points2[:,i] = mult.T

In [14]:
fig = px.scatter(x=points2[0], y=points2[1], labels={'x': 'X', 'y': 'Y'}, title='Transformed Points')
# fig.update_yaxes(scaleanchor="x", scaleratio=1)
# fig.update_xaxes(scaleanchor="y", scaleratio=1)
fig.update_layout(width = 600, height=600)
fig.show()